
### GENERAL SETTINGS ###

# Site settings
title: Hyperties Catalogue
subtitle: Worldwide real-time decentralized communication infra-structure
email: github@rethink-project.eu
description: > # this means to ignore newlines until "baseurl:"
  reTHINK Framework provides the tools to build a global
  real-time decentralized communication infra-structure
  where services are inherently inter-operable.
grant: > # this means to ignore newlines until "baseurl:"
  This project has received funding from the European
  Horizon 2020 Programme for research, technological
  development and demonstration under grant agreement nÂ° 645342
baseurl: "/dev-hyperty" # the subpath of your site, e.g. /blog

twitter_username: rethink_eu
github_username:  reTHINK-project
slack_channel: rethink-project
version: 0.6.1

logo: "/img/logo.png"

# Build settings
markdown: kramdown
permalink: /:title/
# excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

sass:
  style: compressed
  sass_dir: _sass

header_pages:
- icon-github.svg

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  hyperties:
    output: true
    permalink: /hyperties/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###
